### ISSUE TITLE
Variable issues when use_vpn_gateway is set to false

### ISSUE THREAD

**Issue by hmuchaku** [Cloud-Schematics/icse-multiple-vpc-network#2]
Even if use_vpn_gateway is set to false, an error will occur if subnet_name is not specified.
```
 2022/06/22 16:29:04 Terraform plan | Error: Invalid index
 2022/06/22 16:29:04 Terraform plan | 
 2022/06/22 16:29:04 Terraform plan |   on main.tf line 158, in module "vpn_gateway":
 2022/06/22 16:29:04 Terraform plan |  158:   subnet_id         = module.gateway_subnets.subnets[0].id
 2022/06/22 16:29:04 Terraform plan |     ├────────────────
 2022/06/22 16:29:04 Terraform plan |     │ module.gateway_subnets.subnets is empty tuple
 2022/06/22 16:29:04 Terraform plan | 
 2022/06/22 16:29:04 Terraform plan | The given key does not identify an element in this collection value: the
 2022/06/22 16:29:04 Terraform plan | collection has no elements.
```

**Comment by jvallexm** [comment]
please post your variables

**Comment by hmuchaku** [comment]
Thanks,
Each variable has been merged into a larger vpc variable, so it may not be reproducible.
There have been significant changes, but is this repository still under development?
I have the impression that the vpc variables are too large and difficult to use.

**Comment by hmuchaku** [comment]
Sorry, I was confused with following repository.
My issue #1/#2 is for the repository "icse-vpc-network-template"
https://github.com/Cloud-Schematics/icse-vpc-network-template

**Comment by jvallexm** [comment]
@hmuchaku Both of these repos are under development. They are used to create specific custom environments. I have created a lot of minimal input terraform templates for VPC:

- https://github.com/Cloud-Schematics/easy-multizone-vpc
- https://github.com/Cloud-Schematics/easy-multitier-vpc
- https://github.com/Cloud-Schematics/easy-vpc-with-openshift-cluster
- https://github.com/Cloud-Schematics/easy-transit-gateway-vpc
